# Generated by Django 2.2.4 on 2019-08-16 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0004_auto_20190815_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persistentid',
            options={'verbose_name': 'Persistent Id', 'verbose_name_plural': 'Persistent Id'},
        ),
        migrations.AddField(
            model_name='persistentid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
