# Generated by Django 2.2.4 on 2019-09-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0005_auto_20190816_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='original_uid',
        ),
    ]
