# Generated by Django 2.0.13 on 2019-04-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='place_of_birth',
        ),
    ]
