# Generated by Django 3.2.5 on 2021-07-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0002_auto_20190402_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name_plural': 'Accounts'},
        ),
    ]
