# Generated by Django 3.2.18 on 2023-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uniauth_saml2_idp", "0002_auto_20210408_1050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprovider",
            name="attribute_processor",
            field=models.CharField(
                blank=True,
                default="uniauth_saml2_idp.processors.base.BaseProcessor",
                help_text='"package.file.classname", example: "uniauth_saml2_idp.base.processors.BaseProcessor"',
                max_length=256,
            ),
        ),
    ]
