# Generated by Django 3.2.19 on 2023-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth_saml2_idp', '0004_alter_serviceprovider_attribute_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='attribute_mapping',
            field=models.TextField(blank=True, default='{\n    "email": [\n        "mail",\n        "email"\n    ],\n    "givenName": [\n        "givenName",\n        "first_name"\n    ],\n    "mail": [\n        "mail",\n        "email"\n    ],\n    "sn": [\n        "sn",\n        "last_name"\n    ]\n}',
                                   help_text='Attribute that would be release to this SP, in JSON format.', null=True),
        ),
    ]
