# Generated by Django 2.2.2 on 2019-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0002_agreementrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='encrypt_advice_attributes',
            field=models.BooleanField(default=False),
        ),
    ]
