# Generated by Django 2.2.2 on 2019-08-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0007_auto_20190827_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='encrypt_assertions',
            new_name='encrypt_assertion',
        ),
    ]
