# Generated by Django 2.2.2 on 2019-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0008_auto_20190827_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='encrypt_advice_attributes',
            field=models.BooleanField(default=False, help_text='advice element should be encrypted'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='encrypt_assertion',
            field=models.BooleanField(default=False, help_text='encrypt assertion'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='encrypt_assertion_self_contained',
            field=models.BooleanField(default=False, help_text='encrypted assertions should have all namespaces'),
        ),
    ]
