# Generated by Django 2.2.2 on 2019-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0009_auto_20190827_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='encrypt_advice_attributes',
            field=models.BooleanField(default=True, help_text='advice element should be encryptedOnly valid if encrypt assertion is True'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='encrypt_assertion_self_contained',
            field=models.BooleanField(default=True, help_text='encrypted assertions should have all namespaces.Only valid if encrypt assertion is True'),
        ),
    ]
