# Generated by Django 2.2.2 on 2019-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0010_auto_20190827_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='encrypt_advice_attributes',
            field=models.BooleanField(default=True, help_text='advice element should be encrypted. Only valid if encrypt assertion is True'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='encrypt_assertion_self_contained',
            field=models.BooleanField(default=True, help_text='encrypted assertions should have all namespaces. Only valid if encrypt assertion is True'),
        ),
    ]
