# Generated by Django 2.2.2 on 2019-09-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0012_auto_20190902_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='force_attribute_release',
            field=models.BooleanField(default=False, help_text='Release the configured attribute mapping regardless of what SP asks for.'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='attribute_mapping',
            field=models.TextField(blank=True, default='{\n    "cn": "cn",\n    "codice_fiscale": "codice_fiscale",\n    "displayName": [\n        "isdf",\n        "displayName",\n        "cn"\n    ],\n    "eduPersonAffiliation": "eduPersonAffiliation",\n    "eduPersonEntitlement": "eduPersonEntitlement",\n    "eduPersonHomeOrganization": "eduPersonHomeOrganization",\n    "eduPersonPrincipalName": "eduPersonPrincipalName",\n    "eduPersonTargetedID": "eduPersonTargetedID",\n    "givenName": "givenName",\n    "mail": "mail",\n    "matricola_dipendente": "matricola_dipendente",\n    "matricola_studente": "matricola_studente",\n    "schacHomeOrganization": "schacHomeOrganization",\n    "schacPersonalUniqueCode": "schacPersonalUniqueCode",\n    "schacPersonalUniqueID": "schacPersonalUniqueID",\n    "sn": "sn"\n}', help_text='Attribute that would be release to this SP, in JSON format.', null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='attribute_processor',
            field=models.CharField(blank=True, default='idp.processors.LdapUnicalMultiAcademiaProcessor', help_text='"package.file.classname", example: "idp.processors.LdapAcademiaProcessor"', max_length=256),
        ),
    ]
