# Generated by Django 2.2.2 on 2019-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0013_auto_20190903_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='encrypt_advice_attributes',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='encrypt_assertion',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='encrypt_assertion_self_contained',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='disable_encrypted_assertions',
            field=models.BooleanField(default=False, help_text='disable encryption'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='attribute_mapping',
            field=models.TextField(blank=True, default='{\n    "cn": "cn",\n    "codice_fiscale": "codice_fiscale",\n    "displayName": [\n        "isdf",\n        "displayName",\n        "cn"\n    ],\n    "eduPersonAffiliation": "eduPersonAffiliation",\n    "eduPersonEntitlement": "eduPersonEntitlement",\n    "eduPersonHomeOrganization": "eduPersonHomeOrganization",\n    "eduPersonPrincipalName": "eduPersonPrincipalName",\n    "eduPersonTargetedID": "eduPersonTargetedID",\n    "email": [\n        "mail",\n        "email"\n    ],\n    "givenName": "givenName",\n    "mail": [\n        "mail",\n        "email"\n    ],\n    "matricola_dipendente": "matricola_dipendente",\n    "matricola_studente": "matricola_studente",\n    "schacHomeOrganization": "schacHomeOrganization",\n    "schacPersonalUniqueCode": "schacPersonalUniqueCode",\n    "schacPersonalUniqueID": "schacPersonalUniqueID",\n    "sn": "sn"\n}', help_text='Attribute that would be release to this SP, in JSON format.', null=True),
        ),
    ]
